openapi: 3.1.0
info:
  title: PetStore
  version: 1.0.0
paths:
  /pets:
    get:
      description: Returns all pets
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          x-faker: name.firstName
          example: doggie
        photoUrls:
          type: array
          items:
            type: string
            x-faker: image.imageUrl
    Pets:
      type: array
      items:
        $ref: '#/components/schemas/Pet'
